# Generated by Django 5.1.2 on 2024-10-17 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movements", "0001_initial"),
        ("registrations", "0004_alter_product_unit_of_measurement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productentry",
            options={"ordering": ["-update_at"]},
        ),
        migrations.CreateModel(
            name="StockOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "output_type",
                    models.CharField(
                        choices=[("C", "Consumo"), ("P", "Perda"), ("E", "Emprestimo")],
                        max_length=10,
                        verbose_name="Tipo de saída",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de atualização"
                    ),
                ),
                (
                    "list_products",
                    models.ManyToManyField(
                        related_name="outs",
                        to="movements.productentry",
                        verbose_name="Lista de Produtos",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exits",
                        to="registrations.place",
                        verbose_name="Local",
                    ),
                ),
            ],
        ),
    ]
