# Generated by Django 5.1.2 on 2024-10-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Suppliers",
            new_name="Supplier",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="mame",
            new_name="name",
        ),
    ]
