# Generated by Django 5.1.2 on 2024-10-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0003_profile_place_alter_profile_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit_of_measurement",
            field=models.CharField(
                choices=[
                    ("kg", "Quilograma"),
                    ("g", "Grama"),
                    ("un", "Unidade"),
                    ("litro", "Litro"),
                    ("ml", "Mililitro"),
                    ("cx", "Caixa"),
                    ("pc", "Pacote"),
                ],
                max_length=10,
                verbose_name="Unidade de medida",
            ),
        ),
    ]
