# Generated by Django 5.1.2 on 2024-10-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0004_alter_product_unit_of_measurement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="Nome"),
        ),
    ]
